error C2440: 'static_cast': cannot convert from 'double' to 'PassmarkLineType'.
Conversions between enumeration and floating point values are no longer allowed.

--HG--
branch : develop